'use client'
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import imgDil from "@/app/images/Wishlist.png"
import logo from "@/app/images/logo.png"
import corzinka from "@/app/images/corzinka.png"
import social from "@/app/images/social.png"
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuOpen, setMenuOpen] = useState(false);

    const toggleMenu = () => {
        setMenuOpen(!menuOpen);
    };

    const closeMenu = () => {
        setMenuOpen(false);
    };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-white shadow-md fixed mb-[100px] z-10">
                <nav className="flex flex-wrap items-center justify-between max-w-6xl mx-auto p-4">
                    <Link href="/login">
                      <Image src={logo} alt="Logo" className="w-[120px]" />
                    </Link>

                    <div className="hidden md:flex space-x-6">
                        <Link href="/" className="text-gray-700 hover:text-black">
                            Home
                        </Link>
                        <Link href="/contact" className="text-gray-700 hover:text-black">
                            Contact
                        </Link>
                        <Link href="/about" className="text-gray-700 hover:text-black">
                            About
                        </Link>
                        <Link href="/signUp" className="text-gray-700 hover:text-black">
                            Sign Up
                        </Link>
                    </div>

                    <button
                        onClick={toggleMenu}
                        className="md:hidden flex flex-col items-center space-y-1"
                    >
                        <div className="w-6 h-1 bg-black"></div>
                        <div className="w-6 h-1 bg-black"></div>
                        <div className="w-6 h-1 bg-black"></div>
                    </button>

                    {menuOpen && (
                        <div className="md:hidden absolute top-0 left-0 w-full bg-white shadow-md p-4 z-50">
                            <button
                                onClick={closeMenu}
                                className="absolute top-2 right-2 text-xl font-bold"
                            >
                                &times;
                            </button>
                            <div className="space-y-4">
                                <Link href="/" className="block text-lg" onClick={closeMenu}>Home</Link>
                                <Link href="/contact" className="block text-lg" onClick={closeMenu}>Contact</Link>
                                <Link href="/about" className="block text-lg" onClick={closeMenu}>About</Link>
                                <Link href="/signUp" className="block text-lg" onClick={closeMenu}>Sign Up</Link>
                            </div>
                        </div>
                    )}

                    <div className="flex items-center space-x-4">
                        <input
                            type="text"
                            placeholder="What are you looking for?"
                            className="hidden sm:block p-2 border rounded-lg text-sm"
                        />
                        <Link href="/wishlist">
                        <Image src={imgDil} className="w-8 h-8 cursor-pointer" alt="Wishlist" />
                        </Link>
                        <Link href="/cart">
                        <Image src={corzinka} className="w-8 h-8 cursor-pointer" alt="Cart" />
                        </Link>
                    </div>
                </nav>
            </header>

            <main className="max-w-6xl mx-auto p-4">
              {children}
            </main>

            <footer className="w-full bg-black text-white py-10 px-6">
                <div className="max-w-6xl mx-auto flex flex-wrap justify-between gap-6 text-sm sm:text-base py-10">
                    <div className="w-full sm:w-[45%] lg:w-[20%] flex flex-col gap-2">
                        <p className="text-lg font-semibold">Exclusive</p>
                        <p className="mt-2">Subscribe</p>
                        <p className="text-gray-400">Get 10% off your first order</p>
                        <input
                            type="text"
                            placeholder="Enter your email"
                            className="mt-2 p-2 w-full border rounded-lg bg-white text-black"
                        />
                    </div>

                    <div className="w-full sm:w-[45%] lg:w-[20%] flex flex-col gap-2">
                        <p className="text-lg font-semibold">Support</p>
                        <p className="text-gray-400 mt-2">111 Bijoy sarani, Dhaka,  DH 1515, Bangladesh.</p>
                        <p className="text-gray-400">exclusive@gmail.com</p>
                        <p className="text-gray-400">+88015-88888-9999</p>
                    </div>

                    <div className="w-full sm:w-[45%] lg:w-[15%] flex flex-col gap-2">
                        <p className="text-lg font-semibold">Account</p>
                        <p className="text-gray-400 mt-2">My Account</p>
                        <p className="text-gray-400">Cart</p>
                        <p className="text-gray-400">Wishlist</p>
                        <p className="text-gray-400">Shop</p>
                    </div>

                    <div className="w-full sm:w-[45%] lg:w-[15%] flex flex-col gap-2">
                        <p className="text-lg font-semibold">Quick Links</p>
                        <p className="text-gray-400 mt-2">Privacy Policy</p>
                        <p className="text-gray-400">Terms Of Use</p>
                        <p className="text-gray-400">FAQ</p>
                        <p className="text-gray-400">Contact</p>
                    </div>

                    <div className="w-full sm:w-[45%] lg:w-[15%] flex flex-col gap-2">
                        <p className="text-lg font-semibold">Social</p>
                        <div className="mt-2">
                          <Image src={social} alt="Social" className="w-36" />
                        </div>
                    </div>
                </div>
            </footer>
      </body>
    </html>
  );
}
